ax8swap-y += ax8_swap.o arch_arm_mm_fault-armv.o arch_arm_mm_flush.o arch_arm_mm_init.o \
		fs_buffer.o fs_proc_meminfo.o fs_splice.o mm_mincore.o mm_fremap.o \
		mm_shmem.o kernel_fork.o page_io.o swap_state.o swapfile.o thrash.o \
		mm_filemap.o mm_memory.o
obj-$(CONFIG_AX8_SWAP)+= ax8swap.o 

