
extern void ah_init(void);
extern void addrtype_init(void);
extern void comment_init(void);
extern void 2connmark_init(void);
extern void conntrack_init(void);
extern void 2dscp_init(void);
extern void 2ecn_init(void);
extern void esp_init(void);
extern void hashlimit_init(void);
extern void helper_init(void);
extern void icmp_init(void);
extern void iprange_init(void);
extern void length_init(void);
extern void limit_init(void);
extern void mac_init(void);
extern void multiport_init(void);
extern void #2mark_init(void);
extern void owner_init(void);
extern void physdev_init(void);
extern void pkttype_init(void);
extern void policy_init(void);
extern void realm_init(void);
extern void sctp_init(void);
extern void standard_init(void);
extern void state_init(void);
extern void tcp_init(void);
extern void 2tcpmss_init(void);
extern void 2tos_init(void);
extern void 2ttl_init(void);
extern void udp_init(void);
extern void unclean_init(void);
extern void CLASSIFY_init(void);
extern void CONNMARK_init(void);
extern void DNAT_init(void);
extern void LOG_init(void);
extern void #DSCP_init(void);
extern void ECN_init(void);
extern void MASQUERADE_init(void);
extern void MIRROR_init(void);
extern void NETMAP_init(void);
extern void NFQUEUE_init(void);
extern void NOTRACK_init(void);
extern void REDIRECT_init(void);
extern void REJECT_init(void);
extern void #MARK_init(void);
void init_extensions(void) {
	ah_init();
	addrtype_init();
	comment_init();
	2connmark_init();
	conntrack_init();
	2dscp_init();
	2ecn_init();
	esp_init();
	hashlimit_init();
	helper_init();
	icmp_init();
	iprange_init();
	length_init();
	limit_init();
	mac_init();
	multiport_init();
	#2mark_init();
	owner_init();
	physdev_init();
	pkttype_init();
	policy_init();
	realm_init();
	sctp_init();
	standard_init();
	state_init();
	tcp_init();
	2tcpmss_init();
	2tos_init();
	2ttl_init();
	udp_init();
	unclean_init();
	CLASSIFY_init();
	CONNMARK_init();
	DNAT_init();
	LOG_init();
	#DSCP_init();
	ECN_init();
	MASQUERADE_init();
	MIRROR_init();
	NETMAP_init();
	NFQUEUE_init();
	NOTRACK_init();
	REDIRECT_init();
	REJECT_init();
	#MARK_init();
}
