# compile with 
# make CFLAGS_MODULE=-fno-pic modules

obj-m += xperiaz_HYPER.o
#obj-m += xperiaz_abyssplug.o
#obj-m += xperiaz_abyssplugv2.o
#obj-m += xperiaz_adaptive.o
#obj-m += xperiaz_alucard.o
#obj-m += xperiaz_asswax.o
#obj-m += xperiaz_badass.o
#obj-m += xperiaz_dancedance.o
#obj-m += xperiaz_darkness.o
#obj-m += xperiaz_intellidemand.o
#obj-m += xperiaz_lionheart.o
#obj-m += xperiaz_nightmare.o
#obj-m += xperiaz_pegasusq.o
#obj-m += xperiaz_smartassH3.o
#obj-m += xperiaz_wheatley.o
