ax8netfilter-y += ax8_netfilter.o  netfilter_core.o netfilter_nf_queue.o netfilter_nf_sockopt.o netfilter_nf_log.o ipv4_netfilter.o ipv6_netfilter.o \
    ipv4_arp.o  ipv4_ip_input.o  ipv4_ip_output.o ipv4_raw.o  ipv4_xfrm4_output.o \
    ipv4_ip_forward.o    ipv4_ip_sockglue.o  ipv4_xfrm4_input.o \
    core_skbuff.o xfrm_xfrm_output.o
    


    
obj-$(CONFIG_AX8_NETFILTER_MODULE)+= ax8netfilter.o 

