ax8swap-y += ax8_swap.o memory.o mincore.o mmap.o rmap.o page_alloc.o page-writeback.o \
		vmscan.o shmem.o page_io.o swap_state.o swapfile.o thrash.o filemap.o \
		fremap.o swap.o
obj-$(CONFIG_AX8_SWAP)+= ax8swap.o 

