ax8swap-y += ax8_swap.o page_io.o swap_state.o swapfile.o thrash.o ax8swap_mincore.o \
	arch_arm_mm_fault-armv.o arch_arm_mm_flush.o fs_buffer.o fs_splice.o \
	mm_filemap.o mm_page-writeback.o mm_rmap.o mm_vmscan.o arch_arm_mm_init.o \
	mm_memcontrol.o mm_shmem.o
obj-$(CONFIG_AX8_SWAP)+= ax8swap.o 

