ax8swap-y += ax8_swap.o filemap.o fremap.o memory.o mincore.o mmap.o rmap.o page_alloc.o page-writeback.o \
		vmscan.o shmem.o page_io.o swap_state.o swapfile.o thrash.o  \
		swap.o arch_arm_mm_fault-armv.o arch_arm_mm_flush.o  arch_arm_mm_init.o \
		fs_buffer.o fs_proc_meminfo.o kernel_fork.o fs_splice.o
obj-$(CONFIG_AX8_SWAP)+= ax8swap.o 

